MSP-RegProf/MSP-RegProf/MSP/Models/CentroDeSalud.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSP_RegProf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentroDeSalud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CentroDeSalud()
        {
            this.EspecialidadPorCentroDeSalud = new HashSet<EspecialidadPorCentroDeSalud>();
            this.LineaColectivoPorCentroDeSalud = new HashSet<LineaColectivoPorCentroDeSalud>();
        }
    
        public short ID { get; set; }
        public string Nombre { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string EMail { get; set; }
        public string URLImagenDelCentroDeSalud { get; set; }
        public short LocalidadID { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaUltimaActualizacion { get; set; }
    
        public virtual Localidad Localidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EspecialidadPorCentroDeSalud> EspecialidadPorCentroDeSalud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaColectivoPorCentroDeSalud> LineaColectivoPorCentroDeSalud { get; set; }
    }
}

MSP-RegProf/MSP-RegProf/MSP/Controllers/CentroDeSaludController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MSP_RegProf.Models;

namespace MSP_RegProf.Controllers
{
    public class CentroDeSaludController : Controller
    {
        private MSPEntities db = new MSPEntities();

        // GET: CentroDeSalud
        public ActionResult Index()
        {
            var centroDeSalud = db.CentroDeSalud.Include(c => c.Localidad);
            return View(centroDeSalud.ToList());
        }

        // GET: CentroDeSalud/Details/5
        public ActionResult Details(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CentroDeSalud centroDeSalud = db.CentroDeSalud.Find(id);
            if (centroDeSalud == null)
            {
                return HttpNotFound();
            }
            return View(centroDeSalud);
        }

        // GET: CentroDeSalud/Create
        public ActionResult Create()
        {
            ViewBag.LocalidadID = new SelectList(db.Localidad, "ID", "Nombre");
            return View();
        }

        // POST: CentroDeSalud/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nombre,Latitud,Longitud,Direccion,Telefono,EMail,URLImagenDelCentroDeSalud,LocalidadID,Activo,FechaUltimaActualizacion")] CentroDeSalud centroDeSalud)
        {
            if (ModelState.IsValid)
            {
                db.CentroDeSalud.Add(centroDeSalud);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocalidadID = new SelectList(db.Localidad, "ID", "Nombre", centroDeSalud.LocalidadID);
            return View(centroDeSalud);
        }

        // GET: CentroDeSalud/Edit/5
        public ActionResult Edit(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CentroDeSalud centroDeSalud = db.CentroDeSalud.Find(id);
            if (centroDeSalud == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocalidadID = new SelectList(db.Localidad, "ID", "Nombre", centroDeSalud.LocalidadID);
            return View(centroDeSalud);
        }

        // POST: CentroDeSalud/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nombre,Latitud,Longitud,Direccion,Telefono,EMail,URLImagenDelCentroDeSalud,LocalidadID,Activo,FechaUltimaActualizacion")] CentroDeSalud centroDeSalud)
        {
            if (ModelState.IsValid)
            {
                db.Entry(centroDeSalud).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocalidadID = new SelectList(db.Localidad, "ID", "Nombre", centroDeSalud.LocalidadID);
            return View(centroDeSalud);
        }

        // GET: CentroDeSalud/Delete/5
        public ActionResult Delete(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CentroDeSalud centroDeSalud = db.CentroDeSalud.Find(id);
            if (centroDeSalud == null)
            {
                return HttpNotFound();
            }
            return View(centroDeSalud);
        }

        // POST: CentroDeSalud/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(short id)
        {
            CentroDeSalud centroDeSalud = db.CentroDeSalud.Find(id);
            db.CentroDeSalud.Remove(centroDeSalud);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MSP-RegProf/MSP-RegProf/MSP/Controllers/RegProf/CentrosDeSalud/CentroDeSaludController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MSP_RegProf.Models;
using System.Transactions;

namespace MSP_RegProf.Controllers
{
    [Authorize]
    public class CentroDeSaludController : Controller
    {
        private MSPEntities db = new MSPEntities();

        // GET: CentroDeSalud
        public ActionResult Index()
        {
            var centroDeSalud = db.CentroDeSalud.Include(c => c.Localidad);
            return View(centroDeSalud.ToList());
        }

        // GET: CentroDeSalud/Details/5
        public ActionResult Details(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CentroDeSalud centroDeSalud = db.CentroDeSalud.Find(id);
            if (centroDeSalud == null)
            {
                return HttpNotFound();
            }
            return View(centroDeSalud);
        }

        // GET: CentroDeSalud/Create
        public ActionResult Create()
        {
            ViewBag.LocalidadID = new SelectList(db.Localidad, "ID", "Nombre");
            return View();
        }

        // POST: CentroDeSalud/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nombre,Latitud,Longitud,Direccion,Telefono,EMail,URLImagenDelCentroDeSalud,LocalidadID,Activo,FechaUltimaActualizacion")] CentroDeSalud centroDeSalud)
        {
            if (ModelState.IsValid)
            {
                db.CentroDeSalud.Add(centroDeSalud);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocalidadID = new SelectList(db.Localidad, "ID", "Nombre", centroDeSalud.LocalidadID);
            return View(centroDeSalud);
        }

        // GET: CentroDeSalud/Edit/5
        public ActionResult Edit(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CentroDeSalud centroDeSalud = db.CentroDeSalud.Find(id);
            if (centroDeSalud == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocalidadID = new SelectList(db.Localidad, "ID", "Nombre", centroDeSalud.LocalidadID);
            ViewBag.DepartamentoID = new SelectList(db.Departamento, "ID", "Nombre", centroDeSalud.Localidad.DepartamentoID);
            return View(centroDeSalud);
        }

        // POST: CentroDeSalud/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nombre,Latitud,Longitud,Direccion,Telefono,EMail,URLImagenDelCentroDeSalud,LocalidadID,Activo,FechaUltimaActualizacion")] CentroDeSalud centroDeSalud)
        {
            if (ModelState.IsValid)
            {
                db.Entry(centroDeSalud).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocalidadID = new SelectList(db.Localidad, "ID", "Nombre", centroDeSalud.LocalidadID);
            return View(centroDeSalud);
        }

        // GET: CentroDeSalud/Delete/5
        public ActionResult Delete(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CentroDeSalud centroDeSalud = db.CentroDeSalud.Find(id);
            if (centroDeSalud == null)
            {
                return HttpNotFound();
            }
            return View(centroDeSalud);
        }

        // POST: CentroDeSalud/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(short id)
        {
            CentroDeSalud centroDeSalud = db.CentroDeSalud.Find(id);
            db.CentroDeSalud.Remove(centroDeSalud);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }




        // GET: CentroDeSalud/CreateEspecialidad/5
        [Route("CentroDeSalud/CreateEspecialidad/{csId}")]
        [HttpGet]
        public ActionResult CreateEspecialidad(short csId)
        {


            ViewBag.EspecialidadID = new SelectList(db.Especialidad, "ID", "Nombre");
            ViewBag.HorariosID = new SelectList(db.Horarios, "ID", "Hora");

            //EspecialidadPorCentroDeSalud
            //HorariosPorEspecialidadPorCentroDeSalud
            ViewBag.csId = csId;

            return PartialView();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("CentroDeSalud/CreateEspecialidad")]
        public ActionResult CreateEspecialidad(EspecialidadPorCentroDeSalud data)
        {

            //using (TransactionScope tran = new TransactionScope())
            //{

            //}
            try
            {
                var existeEspecialidad = db.CentroDeSalud.Find(data.CentroDeSaludID).EspecialidadPorCentroDeSalud.Any(r => r.EspecialidadID == data.EspecialidadID);

                if (existeEspecialidad)
                {
                    return Json(new {
                        ok = false,
                        msj = "La especialidad seleccionada ya esta asociada al Centro de Salud",
                    });
                }
                

                db.EspecialidadPorCentroDeSalud.Add(data);
                //db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e )
            {

                ViewBag.EspecialidadID = new SelectList(db.Especialidad, "ID", "Nombre");
                ViewBag.HorariosID = new SelectList(db.Horarios, "ID", "Hora");

                //EspecialidadPorCentroDeSalud
                //HorariosPorEspecialidadPorCentroDeSalud

                return PartialView();
            }



            //if (ModelState.IsValid)
            //{
            //    db.EspecialidadPorCentroDeSalud.Add(data);
            //    //db.SaveChanges();
            //    return RedirectToAction("Index");
            //}

            
        }



        // GET: CentroDeSalud/EditEspecialidad/5
        [Route("CentroDeSalud/EditEspecialidad/{EspecialidadPorCentroDeSaludID}")]
        [HttpGet]
        public ActionResult EditEspecialidad(int EspecialidadPorCentroDeSaludID)
        {
            var model = db.EspecialidadPorCentroDeSalud.Where(r => r.ID == EspecialidadPorCentroDeSaludID).FirstOrDefault();

            ViewBag.EspecialidadID = new SelectList(db.Especialidad, "ID", "Nombre");
            ViewBag.HorariosID = new SelectList(db.Horarios, "ID", "Hora");

            //EspecialidadPorCentroDeSalud
            //HorariosPorEspecialidadPorCentroDeSalud
            ViewBag.csId = model.CentroDeSaludID;

            return PartialView(model);
        }















        //Return Partial View
        [Route("CentroDeSalud/EspecialidadesPartial/{csId}")]
        public ActionResult EspecialidadesPartial(short csId)
        {
            var model = db.EspecialidadPorCentroDeSalud.Where(r => r.CentroDeSaludID == csId).ToList();
            return PartialView("_EspecialidadesPartial", model);

        }


    }
}

MSP-RegProf/MSP-RegProf/MSP/Views/CentroDeSalud/Edit.cshtml
@model MSP_RegProf.Models.CentroDeSalud
@using MSP_RegProf.Models
@{
    //Layout = null;
    ViewBag.Title = "Centros de Salud";
    short csId = Model.ID;
}

<style>
    #map {
        height: 500px;
        width: 100%;
    }

    .todo-list li{
        margin-bottom : 0px;
    }

    .todo-list .box {
        margin-bottom: 0px;
    }

    .todo-list li {
        list-style: none;
    }

    .panel-title .btn {
        padding-top: 2px;
        padding-bottom: 2px;
    }

    .todo-list .btn {
        padding-bottom: 0px;
        padding-top: 0px;
    }

    .col-xs-1, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9, .col-xs-10, .col-xs-11, .col-xs-12, .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11, .col-sm-12, .col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-md-10, .col-md-11, .col-md-12, .col-lg-1, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-lg-10, .col-lg-11, .col-lg-12 {
        padding-right: 5px;
        padding-left: 5px;
    }

    .legend {
        border-bottom: 1px solid #3c8dbc;
        display: block;
        width: 100%;
        padding: 0;
        margin-bottom: 20px;
        font-size: 21px;
        line-height: inherit;
        color: #333333;
        border: 0;
    }
</style>


<section class="content-header">
    <h1>
        @Model.Nombre
        <small>Centro de Salud</small>
    </h1>

    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li><a href="@Url.Action("Index","CentroDeSalud")">Centros de Centros de Salud</a></li>
        <li class="active">Editar</li>
    </ol>
</section>

<div class="content">

    <!-- Box - Datos Centro de Salud -->
    <div class="box box-primary">

        <div class="box-header">
            <h3 class="box-title">Datos Generales:</h3>
        </div>

        <div class="box-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <div class="container">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <!-- Grupo - Datos Generales -->
                        <!-- Fila 1 - Nombre y Direccion -->
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label col-md-2 col-md-offset-1" for="Apellido">Nombre:</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label col-md-2 col-md-offset-1" for="Nombre">Direccion:</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Fila 2 - Departamento y Localidad -->
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label col-md-2 col-md-offset-1" for="Depto">Depto:</label>
                                    <div class="col-md-8">
                                        @Html.DropDownList("DepartamentoID", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Localidad.DepartamentoID, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label col-md-2 col-md-offset-1" for="Apellido">Localidad:</label>
                                    <div class="col-md-8">
                                        @Html.DropDownList("LocalidadID", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.LocalidadID, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>


                        <!-- Fila 3 - Telefono y EMail -->
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label col-md-2 col-md-offset-1" for="Apellido">Telefono:</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label col-md-2 col-md-offset-1" for="Apellido">EMail:</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.EMail, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.EMail, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>


                        <!-- Fila 4 - Imagen -->
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label col-md-2 col-md-offset-1" for="Apellido">Imagen:</label>
                                    <div class="col-md-8">
                                        <input type="file" class="form-control" />
                                    </div>
                                </div>
                            </div>
                        </div>



                    </div>
                </div>
            }
        </div>
    </div>


    <!-- Box - Lineas de Colectivos -->
    <div class="box box-primary">

        <div class="box-header">
            <h3 class="box-title">Lineas de Colectivos:</h3>
        </div>

       
    </div>


    <!-- Box - Especialidades y Horarios -->
    @{
        var EspecialidadPorCentroDeSaludModel = new List<EspecialidadPorCentroDeSalud>();

        if (Model.EspecialidadPorCentroDeSalud != null && Model.EspecialidadPorCentroDeSalud.Count > 0)
        {
            EspecialidadPorCentroDeSaludModel = Model.EspecialidadPorCentroDeSalud.ToList();
        }

    }
    <div id="EspecialidadPartial">
        @Html.Partial("_EspecialidadesPartial", EspecialidadPorCentroDeSaludModel, new ViewDataDictionary { { "csId", Model.ID } })
    </div>

    <!-- Box - Lineas de Colectivos -->
    <div class="box box-primary">

        <div class="box-header">
            <h3 class="box-title">Especialidades y Horarios:</h3>
        </div>

        <div class="box-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <div class="container">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <!-- Grupo - Geolocalizacion -->
                        <!-- Fila 1 - Latitud y Longitud -->
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label col-md-2 col-md-offset-1" for="Latitud">Latitud:</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Latitud, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Latitud, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label col-md-2 col-md-offset-1" for="Longitud">Longitud:</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Longitud, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Longitud, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            @*style="display:none"*@
                            <div class="col-md-12">
                                <div id="map"></div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>







<script>
    function initMap() {
        //var uluru = { lat: -25.363, lng: 131.044 };,,7.75z
        var SanJuan = { lat: -30.526, lng: -69.592 };
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 7,
            center: SanJuan
        });
        //var marker = new google.maps.Marker({
        //    position: uluru,
        //    map: map
        //});
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBZK0bGv6wCVNOpLiLRLgV_hy8B-Y07pp4&callback=initMap">
</script>

MSP-RegProf/MSP-RegProf/MSP/Views/CentroDeSalud/Index.cshtml
@model IEnumerable<MSP_RegProf.Models.CentroDeSalud>

@{
    //Layout = null;
    ViewBag.Title = "Centros de Salud";
        
}
<style>
    .modal-lg {
        width: 70%;
    }
</style>



<section class="content-header">
    <h1>
        Centros de Salud
        <small></small>
    </h1>

    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li class="active"> Centros de Salud</li>
    </ol>
</section>

<div class="content">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Listado de Centros de Salud</h3>

            <button type="button" style="margin-right:25px;" class="btn btn-primary btn-md pull-right" data-toggle="modal" data-target="#myModal" onclick="abrirModal('/CentroDeSalud/Create', 'Agregar', 'Centro de Salud')">
                <i class="fa fa-plus"></i> Nuevo
            </button>
        </div>
        <div class="box-body">
            <table id="dtCentroDeSalud" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th style="width:140px">Acciones</th>
                        <th>Nombre</th>
                        @*<th>Latitud</th>*@
                        @*<th>Longitud</th>*@
                        <th>Direccion</th>
                        <th>Telefono</th>
                        <th>EMail</th>
                        @*<th>URLImagenDelCentroDeSalud</th>*@
                        @*<th>Activo</th>*@
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <div class="btn-group-sm">
                                    <span data-placement="top" title="Editar" data-toggle="tooltip">
                                        @*<a class="btn btn-info fa fa-pencil-square-o" data-toggle="modal" data-target="#myModal" onclick="abrirModal('/CentroDeSalud/Edit/@item.ID','Editar','Centro de Salud')"></a>*@
                                        <a href="@Url.Action("Edit","CentroDeSalud",new {id=item.ID})" class="btn btn-info fa fa-pencil-square-o"></a>
                                    </span>

                                    <span data-placement="top" title="Detalles" data-toggle="tooltip">
                                        <a class="btn btn-default fa fa-file-text-o" data-toggle="modal" data-target="#myModal" onclick="abrirModal('/CentroDeSalud/Details/@item.ID','Detalle','Centro de Salud')"></a>
                                    </span>
                                    <span data-placement="top" title="Eliminar" data-toggle="tooltip">
                                        <a class="btn btn-danger fa fa-trash" data-toggle="modal" data-target="#myModal" onclick="abrirModal('/CentroDeSalud/Delete/@item.ID','Eliminar','Centro de Salud')"></a>
                                    </span>
                                </div>
                            </td>
                            <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                            @*<td>@Html.DisplayFor(modelItem => item.Latitud)</td>*@
                            @*<td>@Html.DisplayFor(modelItem => item.Longitud)</td>*@
                            <td>@Html.DisplayFor(modelItem => item.Direccion)</td>
                            <td>@Html.DisplayFor(modelItem => item.Telefono)</td>
                            <td>@Html.DisplayFor(modelItem => item.EMail)</td>
                            @*<td>@Html.DisplayFor(modelItem => item.URLImagenDelCentroDeSalud)</td>*@
                            @*<td>@Html.DisplayFor(modelItem => item.Activo)</td>*@
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(function () {
        if (!$.fn.dataTable.isDataTable('#dtCentroDeSalud')) {
            $('#dtCentroDeSalud').DataTable({
                "language": DataTableEsp()
            });
        }


        $('#myModal').on('show.bs.modal', function (e) {
            debugger
            $("#myModal .modal-dialog").addClass("modal-lg")

        })
    });
</script>