MSP-RegProf/MSP-RegProf/MSP/Models/App Models/RegProf/DigitDocs/DocsVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MSP_RegProf.Models
{
    public class DocsVM
    {
       
        public string docTitulo { get; set; }

        public string docAnalitico { get; set; }

        

    }
}

MSP-RegProf/MSP-RegProf/MSP/Models/App Models/RegProf/DigitDocs/ProfVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MSP_RegProf.Models
{
    public class ProfVM
    {
        public int profId { get; set; }
        public string profDni { get; set; }

        public string profNombre { get; set; }

        public string profApellido { get; set; }

        public string profPais { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime profFechaNac { get; set; }


        public List<TituloProfVM> ListaTitulos { get; set; }



        public static ProfVM GetProfDummy()
        {
            ProfVM Profesional = new ProfVM()
            {
                profId=1,
                profDni = "28558963",
                profNombre = "Pepe",
                profApellido = "Panzas",
                profFechaNac = DateTime.Today
            };

            List<TituloProfVM> ListaTitulos = new List<TituloProfVM> {
               new TituloProfVM() {titId=1,titDenominacion="Medico Clinico",titMatricula="15847"},
               new TituloProfVM() {titId=2,titDenominacion="Traumatologo",titMatricula="92584"},
               new TituloProfVM() {titId=3,titDenominacion="Cirujano",titMatricula="14785"}
            };

            Profesional.ListaTitulos=ListaTitulos;

            return Profesional;
        }

        public static List<ProfVM> GetListaProfDummy()
        {
            List<ProfVM> ListaProfesionales = new List<ProfVM>();

            //Prof nº 1
            ProfVM Profesional = new ProfVM()
            {
                profId = 1,
                profDni = "123456",
                profNombre = "Jose",
                profApellido = "Peralta",
                profFechaNac = DateTime.Today,
                profPais = "Argentina"
            };
            List<TituloProfVM> ListaTitulos = new List<TituloProfVM> {
               new TituloProfVM() {profId = 1,titId=1,titDenominacion="Medico Clinico",titMatricula="15747"},
               new TituloProfVM() {profId = 1,titId=2,titDenominacion="Traumatologo",titMatricula="93284"},
               new TituloProfVM() {profId = 1,titId=3,titDenominacion="Cirujano",titMatricula="17235"}
            };
            Profesional.ListaTitulos = ListaTitulos;
            ListaProfesionales.Add(Profesional);


            //Prof nº 2
            Profesional = new ProfVM()
            {
                profId = 2,
                profDni = "34329291",
                profNombre = "Paulo",
                profApellido = "Garcia",
                profFechaNac = DateTime.Today,
                profPais = "Argentina"
            };
            ListaTitulos = new List<TituloProfVM> {
               new TituloProfVM() {profId = 2,titId=4,titDenominacion="Medico Clinico",titMatricula="87947"},
               new TituloProfVM() {profId = 2,titId=5,titDenominacion="Incologia",titMatricula="92584"},
               new TituloProfVM() {profId = 2,titId=6,titDenominacion="Neurocirujano",titMatricula="112345"}
            };
            Profesional.ListaTitulos = ListaTitulos;
            ListaProfesionales.Add(Profesional);

            //Prof nº 3
            Profesional = new ProfVM()
            {
                profId = 3,
                profDni = "987654",
                profNombre = "Luis",
                profApellido = "Manzano",
                profFechaNac = DateTime.Today,
                profPais = "Chile"
            };
            ListaTitulos = new List<TituloProfVM> {
               new TituloProfVM() {profId = 3,titId=7,titDenominacion="Medico Clinico",titMatricula="15847"},
               new TituloProfVM() {profId = 3,titId=8,titDenominacion="Traumatologo",titMatricula="92584"},
               new TituloProfVM() {profId = 3,titId=9,titDenominacion="Cirujano",titMatricula="14785"}
            };
            Profesional.ListaTitulos = ListaTitulos;
            ListaProfesionales.Add(Profesional);

            //Prof nº 4
            Profesional = new ProfVM()
            {
                profId = 4,
                profDni = "147258",
                profNombre = "Pepe",
                profApellido = "Panzas",
                profFechaNac = DateTime.Today,
                profPais = "Peru"
            };
            ListaTitulos = new List<TituloProfVM> {
               new TituloProfVM() {profId = 4,titId=10,titDenominacion="Medico Clinico",titMatricula="15847"},
               new TituloProfVM() {profId = 4,titId=11,titDenominacion="Traumatologo",titMatricula="92584"},
               new TituloProfVM() {profId = 4,titId=12,titDenominacion="Cirujano",titMatricula="14785"}
            };
            Profesional.ListaTitulos = ListaTitulos;
            ListaProfesionales.Add(Profesional);

            //Prof nº 5
            Profesional = new ProfVM()
            {
                profId = 5,
                profDni = "369258",
                profNombre = "Carlos",
                profApellido = "Mas",
                profFechaNac = DateTime.Today,
                profPais = "Argentina"
            };
            ListaTitulos = new List<TituloProfVM> {
               new TituloProfVM() {profId = 5,titId=13,titDenominacion="Medico Clinico",titMatricula="15847"},
               new TituloProfVM() {profId = 5,titId=14,titDenominacion="Traumatologo",titMatricula="92584"},
               new TituloProfVM() {profId = 5,titId=15,titDenominacion="Cirujano",titMatricula="14785"}
            };
            Profesional.ListaTitulos = ListaTitulos;
            ListaProfesionales.Add(Profesional);

            //Prof nº 6
            Profesional = new ProfVM()
            {
                profId = 6,
                profDni = "741852",
                profNombre = "Pepe",
                profApellido = "Panzas",
                profFechaNac = DateTime.Today,
                profPais = "Argentina"
            };
            ListaTitulos = new List<TituloProfVM> {
               new TituloProfVM() {profId = 6,titId=16,titDenominacion="Medico Clinico",titMatricula="15847"},
               new TituloProfVM() {profId = 6,titId=17,titDenominacion="Traumatologo",titMatricula="92584"},
               new TituloProfVM() {profId = 6,titId=18,titDenominacion="Cirujano",titMatricula="14785"}
            };
            Profesional.ListaTitulos = ListaTitulos;
            ListaProfesionales.Add(Profesional);


            return ListaProfesionales;
        }

    }
}

MSP-RegProf/MSP-RegProf/MSP/Models/App Models/RegProf/DigitDocs/TituloProfVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MSP_RegProf.Models
{
    public class TituloProfVM
    {
        public int titId { get; set; }

        public int profId { get; set; }

        public string titDenominacion { get; set; }

        public string titMatricula { get; set; }

        public bool existeDoc { get; set; }
    }
}

MSP-RegProf/MSP-RegProf/MSP/Controllers/RegProf/DigitDocs/DigitDocsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MSP_RegProf.Models;
using System.IO;
using WebGrease.Activities;
using System.Data.Entity;

namespace MSP_RegProf.Controllers
{
    [Authorize]
    public class DigitDocsController : Controller
    {
        private MSPEntities db = new MSPEntities();

        // GET: DigitDocs
        public ActionResult Index()
        {
            var model = ProfVM.GetProfDummy();

            return View(model);
        }

        // POST: DigitDocs/BuscaProf/{dni}
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult BuscaProf(string profDni)
        {
            //Implementar Busqueda del Profecional
            //var Profesional = ProfVM.GetListaProfDummy().Where(r => r.profDni == profDni).FirstOrDefault();

            profDni = profDni.Trim();
            var Profesional = db.Persona.Include(r => r.Matricula).Where(r => r.NroDocumento == profDni).FirstOrDefault();

            if (Profesional == null)
            {
                return Json(new
                {
                    ok = "false",
                    mensaje = "DNI incorrecto o Profesional no registrado"
                });
            }

            return PartialView("_datosProf", Profesional);
        }


        // GET: DigitDocs/SubirDocs
        [Route("DigitDocs/SubirDocs/{perId}/{matId}")]
        [HttpGet]
        public ActionResult SubirDocs(int perId, int matId)
        {
            //var titulo = ProfVM.GetListaProfDummy().Where(r => r.profId == profId).FirstOrDefault().ListaTitulos.Where(r => r.titId == titId).FirstOrDefault();

            //var titulo = db.Persona.FirstOrDefault(r => r.ID == perId).Matricula.FirstOrDefault(r => r.NroMatricula == matId);
            var Matricula = db.Matricula.FirstOrDefault(r => r.ID == matId);
            return PartialView(Matricula);
        }

        // POST: DigitDocs/Create
        [Route("DigitDocs/SubirDocs/{perId}/{matId}")]
        [HttpPost]
        public ActionResult SubirDocs(HttpPostedFileBase docTitulo, HttpPostedFileBase docAnalitico, int perId, int matId)//
        {
            try
            {
                //var profesional = ProfVM.GetListaProfDummy().Where(r => r.profId == perId).FirstOrDefault();
                var Matricula = db.Matricula.FirstOrDefault(r => r.ID == matId);
                Matricula.FechaActualizacion = DateTime.Now;

                if (Request.Files.Count > 0)
                {
                    HttpFileCollectionBase files = Request.Files;
                    //string _IdMatricula = profesional.profId.ToString()+"_"+ profesional.ListaTitulos.Where(r=>r.titId== matId).FirstOrDefault().titMatricula.ToString();
                    string _IdMatricula = Matricula.PersonaID.ToString() + "_" + Matricula.NroMatricula.ToString();

                    //Titulo
                    if (files["docTitulo"] != null)
                    {
                        docTitulo = files["docTitulo"];

                        if (docTitulo.ContentLength > 0)
                        {
                            string _FileName = _IdMatricula + "_Titulo" + Path.GetExtension(docTitulo.FileName);
                            System.IO.Directory.CreateDirectory(Server.MapPath("~/UploadedFiles/Profesionales/" + Matricula.PersonaID.ToString() + "/"+ _IdMatricula));
                            string _path = Path.Combine(Server.MapPath("~/UploadedFiles/Profesionales/" + Matricula.PersonaID.ToString() + "/" + _IdMatricula), _FileName);
                            docTitulo.SaveAs(_path);
                            Matricula.TieneTitulo = true;
                        }
                        ViewBag.Message1 = "Titulo subido correctamente!!";
                    }

                    //Analitico
                    if (files["docAnalitico"] != null)
                    {
                        docAnalitico = files["docAnalitico"];

                        if (docAnalitico.ContentLength > 0)
                        {
                            string _FileName = _IdMatricula + "_Analitico" + Path.GetExtension(docAnalitico.FileName);
                            System.IO.Directory.CreateDirectory(Server.MapPath("~/UploadedFiles/Profesionales/" + Matricula.PersonaID.ToString() + "/" + _IdMatricula));
                            string _path = Path.Combine(Server.MapPath("~/UploadedFiles/Profesionales/" + Matricula.PersonaID.ToString() + "/" + _IdMatricula), _FileName);
                            docAnalitico.SaveAs(_path);
                            Matricula.TieneAnalitico = true;
                        }
                        ViewBag.Message2 = "Analitico subido correctamente!!";
                    }

                    db.SaveChanges();
                    return PartialView();
                }
                else
                {
                    ViewBag.Message = "No se subio ningun archivo.";
                    return PartialView();
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message1 = null;
                ViewBag.Message2 = null;
                ViewBag.Message = "Ocurrio un error! Intente nuevamente.\n Mensaje: "+ ex.Message??ex.InnerException.Message;
                return PartialView();
            }
        }


        // GET: DigitDocs/SubirDocs
        [Route("DigitDocs/VerDocs/{perId}/{matId}")]
        [HttpGet]
        public ActionResult VerDocs(int perId, int matId)
        {
            //var titulo = ProfVM.GetListaProfDummy().Where(r => r.profId == perId).FirstOrDefault().ListaTitulos.Where(r => r.titId == matId).FirstOrDefault();
            var Matricula = db.Matricula.FirstOrDefault(r => r.ID == matId);
            return PartialView(Matricula);
        }

        // GET: DigitDocs/SubirDocs
        [Route("DigitDocs/VerDocs/{tipoDoc}/{perId}/{matId}")]
        [HttpGet]
        public FileContentResult VerDocs(string tipoDoc, int perId, int matId)
        {
            var Matricula = db.Matricula.FirstOrDefault(r => r.ID == matId);
            string _IdMatricula = Matricula.PersonaID.ToString() + "_" + Matricula.NroMatricula.ToString();

            //var profesional = ProfVM.GetListaProfDummy().Where(r => r.profId == profId).FirstOrDefault();
            //string _IdMatricula = profesional.profId.ToString() + "_" + profesional.ListaTitulos.Where(r => r.titId == matId).FirstOrDefault().titMatricula.ToString();

            switch (tipoDoc)
            {
                case "docTitulo":
                    {
                        var fullPathToFile = Server.MapPath("~/UploadedFiles/Profesionales/" + Matricula.PersonaID.ToString() + "/" + _IdMatricula + "/" + _IdMatricula + "_Titulo.pdf");
                        var mimeType = "application/pdf";
                        var fileContents = System.IO.File.ReadAllBytes(fullPathToFile);

                        return new FileContentResult(fileContents, mimeType);
                    }
                    //break;

                case "docAnalitico":
                    {
                        var fullPathToFile = Server.MapPath("~/UploadedFiles/Profesionales/" + Matricula.PersonaID.ToString() + "/" + _IdMatricula + "/" + _IdMatricula + "_Analitico.pdf");
                        var mimeType = "application/pdf";
                        var fileContents = System.IO.File.ReadAllBytes(fullPathToFile);

                        return new FileContentResult(fileContents, mimeType);
                    }
                    //break

                default:
                    return null;
                    //break;
            }



        }

        // GET: DigitDocs/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DigitDocs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DigitDocs/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: DigitDocs/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DigitDocs/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: DigitDocs/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DigitDocs/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MSP-RegProf/MSP-RegProf/MSP/Views/DigitDocs/Index.cshtml
@model MSP_RegProf.Models.ProfVM

@{
    ViewBag.Title = "Registro de Profesionales";
}
<style>
    .user-img {
        height: auto;
        width: 90px;
    }
</style>





<section class="content-header">
    <h1>
        Digitalizacion
        <small>de documentos</small>
    </h1>

    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li><a href="#">Registro de Profesionales</a></li>
        <li class="active">Digitalizacion de docs.</li>
    </ol>
</section>


<section class="content">
    <!--Busqueda de Profesional-->
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Busqueda</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">

            <div class="row">
                <!--Formulario-->
                <div class="col-md-5 col-md-offset-1">
                    @using (Html.BeginForm("buscaProf", "DigitDocs", FormMethod.Post, new { @id = "formBusqueda" }))
                    {
                    @Html.AntiForgeryToken()
                    <div class="form">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            @*@Html.LabelFor(model => model.IdEstablecimiento, "IdEstablecimiento", htmlAttributes: new { @class = "control-label col-md-2" })*@
                            <label class="control-label " for="Firma">Busqueda por DNI:</label>

                            <input type="text" id="profDni" required />
                            @*@Html.ValidationMessageFor(model => model.IdEstablecimiento, "", new { @class = "text-danger" })*@

                            <button id="btnBusca" class="btn btn-primary">Buscar</button>
                        </div>
                    </div>
                      }
                </div>

                <!--Mensaje-->
                <div class="col-md-6">
                    <div class="alert alert-danger alert-dismissible" id="contentMsg" style="display:none;">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-ban"></i> Atencion!</h4>
                        <p id="msg"></p>

                    </div>
                </div>
            </div>


        </div>
    </div>
    <!--Fin Busqueda de Profesional-->
    <!--Datos de Profesional-->
    <div class="row" id="contenTitulos">

    </div>
    <!--Fin Datos de Profesional-->

</section>


<script>
    $(function () {
        $('#formBusqueda').submit(function (e) {
            //$('#btnBusca').click(function (e) {
            ////debugger
            var _url = GetPathApp("/DigitDocs/BuscaProf");

            Pace.track(function () {
                $.ajax({
                    method: "POST",
                    url: _url,
                    data: { profDni: $('#profDni').val(), __RequestVerificationToken: $("input[name='__RequestVerificationToken']").val() },
                    beforeSend: function (xhr) {

                        $('#contentMsg').hide();
                        $('#contenTitulos').empty();
                    },
                    success: function (result) {
                        ////debugger
                        if (result.ok == "false") {

                            $('#contenTitulos').empty();
                            $('#contentMsg').show();
                            $('#contentMsg p').text(result.mensaje);
                        }
                        else {
                            $('#contentMsg').hide();
                            $('#contenTitulos').html(result);
                        }

                    }
                });
            });

            e.preventDefault();
        });//Fin "submit"


    });



</script>

MSP-RegProf/MSP-RegProf/MSP/Views/DigitDocs/SubirDocs.cshtml
@model MSP_RegProf.Models.Matricula


@*@using (Html.BeginForm())*@
@using (Html.BeginForm("SubirDocs", "DigitDocs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @if (!string.IsNullOrEmpty(((string)@ViewBag.Message)))
        {
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                @ViewBag.Message
            </div>
        }

        <div class="form-group">
            <label class="control-label col-md-3" for="Firma">Titulo:</label>
            <div class="col-md-8 ">
                @Html.TextBox("docTitulo", "", htmlAttributes: new { @class = "form-control fileUpload", type = "file", accept = ".pdf" })
                <p class="text-success">@ViewBag.Message1</p>
            </div>
        </div>

        <div class="form-group">

            <label class="control-label col-md-3" for="Firma">Analítico:</label>
            <div class="col-md-8 ">
                @Html.TextBox("docAnalitico", "", htmlAttributes: new { @class = "form-control fileUpload", type = "file", accept = ".pdf" })
                <p class="text-success">@ViewBag.Message2</p>
            </div>
        </div>

        @*@Html.HiddenFor(model=>Model.titId)*@
        @*@Html.HiddenFor(model => Model.titId)*@

    </div>
}


<script>
    $(function () {
        //Click "Guardar"
        $("#btnGuardar").unbind("click");
        $("#btnGuardar").click(function () {
            ////debugger
            $('#contenidoModal form').submit()
        });

        //Submit
        $('form').submit(function () {
            //debugger
            // Checking whether FormData is available in browser
            if (window.FormData !== undefined) {
                // Create FormData object
                var fileData = new FormData();

                //File 1
                var fileUpload1 = $("#docTitulo").get(0);
                if (fileUpload1.files.length) {
                    var file1 = fileUpload1.files;
                    fileData.append("docTitulo", file1[0]);
                }

                //File 2
                var fileUpload2 = $("#docAnalitico").get(0);
                if (fileUpload2.files.length) {
                    var file2 = fileUpload2.files;
                    fileData.append("docAnalitico", file2[0]);
                }
            }


            //debugger
            if ($(this).valid()) {
                $.ajax({
                    url: this.action,
                    type: this.method,
                    contentType: false, // Not to set any content header
                    processData: false, // Not to process data
                    data: fileData,
                    beforeSend: function (xhr) {
                        abrirWaiting();
                    },
                    success: function (result) {
                        ////debugger
                        $("#contenidoModal").html(result);
                        cerrarWaiting();
                    },
                });
            }
            return false;
        });
    });

</script>

MSP-RegProf/MSP-RegProf/MSP/Views/DigitDocs/VerDocs.cshtml
@model MSP_RegProf.Models.Matricula


@if (Model.TieneTitulo || Model.TieneAnalitico)
{
    <div class="form-horizontal">

        @if (Model.TieneTitulo)
        {
            <div class="form-group">
                <label class="control-label col-md-4" for="Firma">Titulo:</label>
                <div class="col-md-4 ">
                    <button id="docTitulo" class="btn btn-primary btn-block">Ver</button>
                </div>
            </div>
        }

        @if (Model.TieneAnalitico)
        {
            <div class="form-group">
                <label class="control-label col-md-4" for="Firma">Analítico:</label>
                <div class="col-md-4 ">
                    <button id="docAnalitico" class="btn btn-primary btn-block">Ver</button>
                </div>
            </div>
        }
        
        @Html.HiddenFor(model => Model.ID)
        @Html.HiddenFor(model => Model.PersonaID)
    </div>
}
else
{
    <div class="alert alert-warning alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-warning"></i> Atencion!</h4>
        No existen Documentos en formato digital asociados a esta Matricula.
    </div>
}


    <script>
        $(function () {

            //Click "Ver Titulo"
            $("#docTitulo").click(function () {
                //debugger
                verDoc("docTitulo");
            });

            //Click "Ver Analitico"
            $("#docAnalitico").click(function () {
                //debugger
                verDoc("docAnalitico");
            });

            //Ver Documento
            function verDoc(_tipoDoc) {

                debugger
                var _data = {
                    tipoDoc: _tipoDoc,
                    matId: $("#ID").val(),
                    perId: $("#PersonaID").val()
                };

                var _src = GetPathApp("/DigitDocs/VerDocs/" + _data.tipoDoc + "/" + _data.perId + "/" + _data.matId + "/");
                window.open(_src);

            }

        });

    </script>

MSP-RegProf/MSP-RegProf/MSP/Views/DigitDocs/_datosProf.cshtml
@model MSP_RegProf.Models.Persona


<!--Datos de Personales-->
<div class="col-md-3">
    <div class="box box-primary">
        <div class="box-body box-profile">
            <img class="profile-user-img img-responsive img-circle user-img" src="~/Content/img/nopic.png" alt="User profile picture">

            <h3 class="profile-username text-center">@Model.Nombre @Model.Apellido</h3>

            <p class="text-muted text-center">Profesional</p>

            <ul class="list-group list-group-unbordered">
                <li class="list-group-item">
                    <b>DNI:</b> <a class="pull-right">@Model.NroDocumento</a>
                </li>
                <li class="list-group-item">
                    <b>Fecha Nacimiento</b> <a class="pull-right">@Html.DisplayFor(Model => Model.FechaNacimiento)</a>
                </li>
                <li class="list-group-item">
                    <b>Nacionalidad</b> <a class="pull-right">@Html.DisplayFor(Model => Model.Pais.Nombre)</a>
                </li>
            </ul>

            <a href="#" class="btn btn-primary btn-block"><b>Editar Datos</b></a>
        </div>
        <!-- /.box-body -->
    </div>
</div>
<!--Datos de Personales-->
<!--Datos de Titulos-->
<div class="col-md-9">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Listado de Titulos</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            
            <!-- Button trigger modal -->
            @*<button type="button" style="margin-bottom: 15px;" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal" onclick="abrirModal('/Certificado/Create', 'Agregar', 'Certificado')">
                    <i class="fa fa-plus"></i> Nuevo
                </button>*@
            @if (Model.Matricula.Count > 0)
            {
                <table id="dtCertificados" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th class="text-center">
                                Denominacion
                            </th>
                            <th class="text-center">
                                Matricula
                            </th>
                            <th class="text-center">
                                Libro
                            </th>
                            <th class="text-center">
                                Folio
                            </th>
                            <th class="text-center">
                                Acciones
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var Matricula in Model.Matricula)
                {
                            <tr>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => Matricula.Titulo.Descripcion)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => Matricula.NroMatricula)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => Matricula.libro)
                                </td>
                                <td class="text-center">
                                    @Html.DisplayFor(modelItem => Matricula.Folio)
                                </td>
                                <td>
                                    <div class="btn-group-sm text-center">
                                        <a class="btn btn-default fa fa-upload" data-toggle="modal" data-target="#myModal" onclick="abrirModal('/DigitDocs/SubirDocs/@Model.ID/@Matricula.ID','Cargar','Documentos')"></a>
                                        <a class="btn btn-primary fa fa-eye" data-toggle="modal" data-target="#myModal" onclick="abrirModal('/DigitDocs/VerDocs/@Model.ID/@Matricula.ID','Detalle','Documentos')"></a>
                                        @*<a class="btn btn-danger fa fa-trash" data-toggle="modal" data-target="#myModal" onclick="abrirModal('/DigitDocs/Delete/@item.titId','Eliminar','Certificado')"></a>
                                            <a class="btn btn-primary fa fa-print" onclick="reporte(@item.titId)"></a>*@
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
            }
            else
            {
                <!--Mensaje-->
                <div>
                    <div class="alert alert-info alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-info"></i> Atencion!</h4>
                        <p>No existen Titulos registrados para este profesional.</p>
                    </div>
                </div>
            }


    </div>
    <!-- /.box-body -->
</div>
</div>
<!--Datos de Titulos-->